# Generated by Django 4.0.4 on 2022-05-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(blank=True, choices=[('Куплю', 'Куплю'), ('Продам', 'Продам'), ('Обменяю', 'Обменяю')], max_length=50, verbose_name='Тип'),
        ),
    ]
